#!/bin/bash
source PKGBUILD


## package update
makepkg --skipinteg --noextract -f &&
mkdir -p ../repository/$arch/ &&
mv "$pkgname-$pkgver-1-x86_64.pkg.tar.zst" ../repository/$arch/ &&
git pull &&
git add . &&
git commit -m "update" &&
git push && 


## repository update
cd ../repository/$arch/ &&
repo-add yuros.db.tar.gz *.pkg.tar.zst &&
git pull &&
git add . &&
git commit -m "update" &&
git push 